In [241]:
import os
from PIL import Image
import numpy as np
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import warnings

warnings.filterwarnings('default')

In [196]:
def read_data(dir_img_path):
    X_sample = []
    Y_sample = []
    g = os.walk(dir_img_path)  
    for path,dir_list,file_list in g:  
        for file_name in file_list:  
            img_path = os.path.join(path, file_name)
            img_tag = int(file_name.split('.')[0][-2:])
            img = Image.open(img_path)
            img_array = np.array(img).flatten().tolist()
            X_sample.append(img_array)
            Y_sample.append(img_tag)
    return np.array(X_sample), np.array(Y_sample)

In [246]:
def fisherface(X_train, X_test, y_train, y_test, c):
    N = X_train.shape[0]
    pca = PCA(n_components=80)
    X_train = pca.fit_transform(X_train)
    X_test = pca.transform(X_test)
    
#     print(X_train.shape)
#     print(X_test.shape)
#     print(y_train.shape)
#     print(y_test.shape)
    
    lda = LinearDiscriminantAnalysis(n_components=c-1)
    X_train = lda.fit_transform(X_train, y_train)
    X_test = lda.transform(X_test)
    
    neigh = KNeighborsClassifier()
    neigh.fit(X_train, y_train)
    prediction = neigh.predict(X_test)
    
    return accuracy_score(y_test, prediction)

In [231]:
X_sample, y_sample = read_data(r'D:\2020Spring\DataAlgorithm\resource\yalefaces')
num_classes = 15
N = X_sample.shape[0]

In [247]:
kf = KFold(n_splits=int(N))
accuracies = []
i = 0
for train_index, test_index in kf.split(X_sample):
    print(i)
    i = i + 1
    X_train, X_test = X_sample[train_index], X_sample[test_index]
    y_train, y_test = y_sample[train_index], y_sample[test_index]
    result = fisherface(X_train, X_test, y_train, y_test, num_classes)
    accuracies.append(result)
np.mean(accuracies)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164


0.9696969696969697

In [193]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=4)
print(kf)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)
    print(X_test)
    print(y_train)
    print(y_test)

KFold(n_splits=4, random_state=None, shuffle=False)
TRAIN: [1 2 3] TEST: [0]
[[3 4]
 [5 6]
 [7 8]]
[[1 2]]
[2 3 4]
[1]
TRAIN: [0 2 3] TEST: [1]
[[1 2]
 [5 6]
 [7 8]]
[[3 4]]
[1 3 4]
[2]
TRAIN: [0 1 3] TEST: [2]
[[1 2]
 [3 4]
 [7 8]]
[[5 6]]
[1 2 4]
[3]
TRAIN: [0 1 2] TEST: [3]
[[1 2]
 [3 4]
 [5 6]]
[[7 8]]
[1 2 3]
[4]


SyntaxError: invalid syntax (<ipython-input-186-b5f5e6ebb614>, line 2)